### ISSUE TITLE
v0.2.8 checklist

### ISSUE THREAD

**Issue by aaronwolen** [ropensci/osfr#103]
- [x] Add multi-file transfer functionality to README and vignettes
- [x] Add logging instructions to CONTRIBUTING
- [x] Is `osf_rm()`'s recurse argument still necessary? (on hold https://github.com/CenterForOpenScience/osf.io/issues/9252)

    Leaving it for now as a protection against accidentally deleting a non-empty project.

**Comment by aaronwolen** [comment]
Done!
